config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :categories
  
  resources :lists
	
  resources :homes
	
  resources :detaileds

  resources :products

  get '/order/:id(.:format)' => 'cartpages#order', as: :order

  get '/new(.:format)' => 'cartpages#new', as: :newcart

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :set_category, only: [:show]
  before_action :set_common_variables
	  def index
  	end
  	def show
  	end
  	private
    def set_common_variables
      @categories = Category.all
      @products = Product.all
      @popular = Product.popular
      @new_arrivals = Product.new_arrivals
      @best_sellers = Product.best_sellers
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @cateproduct = Product.where(category_id: @category.id) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :introduce)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/show.html.erb
	<div class="container">
		<div class ="list-top-back">
			<%= link_to "", homes_path, class: "glyphicon glyphicon-home"%>
			<span  class="text-capitalize"><%= @category.name %></span>
		</div>
		<%- model_class = Product -%>
		<div class="row">
			<div class="list-element">
				<div class="col-md-9 pull-right">
					<div class="list-element-top">
						<div class="row">
							<div class="col-md-3">
								<% @cateproduct.each do |product| %>
									<%= image_tag(product.images, alt:"images")%>
									<% break %>
								<% end %>
							</div>
							<div class="col-md-9">
								<p class="text-uppercase"><%= @category.name %></p>
								<span><%= @category.introduce%></span>
							</div>
						</div>
					</div>
					<div class="list-element-bottom">
						<div class="row">
						<% @cateproduct.each do |product|  %>	
							<div class="col-md-4 pull-right">
								<div class="tabs-element">
									<div class="content-tab-images">
										<%= link_to image_tag(product.images, alt: "images"), detailed_path(product) %>
									</div>
									<div class="content-tab-name">
										<%= link_to product.name, detailed_path(product) %>
										<p class="pride"><%= product.price %></p>
									</div>
									<div class="content-tab-button">
										<%= link_to order_path(product), class: "btn btn-default btn-lg" do %>
  											<span class="glyphicon glyphicon-shopping-cart pull-left" aria-hidden="true"></span>ADD TO CART
										<% end %>
										MORE
									</div>
								</div>
							</div>
							<% end %>
						</div>
					</div>
				</div>
				<div class="col-md-3 pull-left">
					<div class="list-element-left">
						<div class="list-box">
							<p>POPULAR</p>
							<%	dem =0	%>
								<% @popular.each do |product| %>
									<% dem += 1 %>
								<div class="list-element-left-box">
									<div class="row">
										<div class="col-md-5">
											<%= link_to image_tag(product.images, alt:"images"), detailed_path(product) %>
										</div>
										<div class="col-md-7">
											<dl>
												<dt><%= link_to product.name, detailed_path(product) %></dt>
												<dd>$ <%= product.price %></dd>
											</dl>
										</div>
									</div>
								</div>
								<% break if dem == 3 %>
							<% end %>
						</div>
						<div class="list-box">
							<p>BEST SELLERS</p>
							<%	dem =0	%>
								<% @best_sellers.each do |product|%>
									<% dem += 1 %>
								<div class="list-element-left-box">
									<div class="row">
										<div class="col-md-5">
											<%= link_to image_tag(product.images, alt:"images"), detailed_path(product) %>
										</div>
										<div class="col-md-7">
											<dl>
												<dt><%= link_to product.name, detailed_path(product) %></dt>
												<dd>$ <%= product.price %></dd>
											</dl>
										</div>
									</div>
								</div>
								<% break if dem == 3 %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>